module.exports = {
  bracketSpacing: true,
  jsxBracketSameLine: true,
  singleQuote: true,
  trailingComma: 'all',
  arrowParens: 'avoid',
  tabWidth: 2,
  printWidth: 150,
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(react-native/(.*)$)|^(react-native$)',
    '',
    '<BUILTIN_MODULES>',
    '<THIRD_PARTY_MODULES>',
    '',
    '^&/animations/(.*)$|^(&/animations)',
    '^&/app/(.*)$|^(&/app)',
    '^&/assets/(.*)$|^(&/assets)',
    '^&/components/(.*)$|^(&/components$)',
    '^&/contexts/(.*)$|^(&/contexts)',
    '^&/hooks/(.*)$|^(&/hooks)',
    '^&/navigators/(.*)$|^(&/navigators)',
    '^&/queries/(.*)$|^(&/queries)',
    '^&/screens/(.*)$|^(&/screens)',
    '^&/services/(.*)$|^(&/services)',
    '^&/stores/(.*)$|^(&/stores)',
    '^&/themes/(.*)$|^(&/themes)',
    '^&/translations/(.*)$|^(&/translations)',
    '^&/types/(.*)$|^(&/types)',
    '^&/utils/(.*)$|^(&/utils)',
    '',
    '^&/__mocks__/(.*)$|^(&/__mocks__)',
    '^&/__tests__/(.*)$|^(&/__tests__)',
    '&/.*',
    '',
    '^[./]',
  ],
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
};
